sudo: false
language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - platform-tools

    - build-tools-23.0.2
    - android-23

    - sys-img-armeabi-v7a-android-23
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - '.+'
env:
  global:
    - ADB_INSTALL_TIMEOUT=8

branches:
  only:
    - master
    - stable

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
