language: android
jdk: oraclejdk7

android:
  components:
      - tools
      - platform-tools

      - build-tools-23.0.2
      - android-23

      - sys-img-armeabi-v7a-android-23
      - extra-android-m2repository
      - extra-android-support
  licenses:
      - '.+'
branches:
  only:
    - master
    - stable
